### ISSUE TITLE
Wouldn't this addon work in version 2.1.26+?

### ISSUE THREAD

**Issue by cjdduarte** [wxxedu/obsidianki4#3]
I would like to congratulate you for this addon.
I wonder if you have tested this addon in previous versions?

Many users are still at least in the .26 version due to some other incompatibilities.

**Comment by wxxedu** [comment]
Thanks so much for your warm words! This is the first real project that I coded. The add-on would not work with previous versions, and it is due to the fact that I used `card_ids_of_note()` function, which isn't in the previous versions of Anki. As I somehow do not know how to download the code for previous versions of Anki, I could not add the correct function. I will try my best to get this sorted out in a couple days.

For now, I think you could install both versions of Anki, and then import the files in the newer version, and review the notes in the old version.

**Comment by cjdduarte** [comment]
è uma I will try this paleative solution. Thanks

**Comment by wxxedu** [comment]
Would you like to help me test 2.1.26? I think it may work with it now. Thanks!

**Comment by cjdduarte** [comment]
Yes! I can. What do you need?

**Comment by cjdduarte** [comment]
I saw here that you made some changes, though:

1 - I use version 2.1.26 (it is the version that several other add-ons are stopped). In your text, you comment that it is for testing in version 2.1.28.

![image](https://user-images.githubusercontent.com/42243532/104809942-f9756800-57cf-11eb-8c51-f7a4236ef9a3.png)

**Comment by wxxedu** [comment]
Oh, I just want to see if it works on that version. I am on an M1 Mac, which unfortunately cannot install older versions😂😂😂. I will adjust this label to older versions. 

I also added a few new features. Just tell me any problems that you've found. hhh. 

Something that I forgot to say in the readme.md is that this Add-on is designed in a way that I expect all the changes (including the deletion and addition of notes) to be made in Obsidian. I added a trash can folder so that if you want to delete something and synchronize the deletion to anki, you could should drag the file to the trash folder instead of deleting them directly.
